### ISSUE TITLE
--match <tag> causes "--dirty is incompatible with commit-ishes"

### ISSUE THREAD

**Issue by msarahan** [python-versioneer/python-versioneer#122] opened 2016-08-16 01:32 UTC
This seems to only affect me on Windows.  Versioneer v.0.16.

At https://github.com/warner/python-versioneer/blob/master/src/git/from_vcs.py#L32 - the addition of the --match argument with the tag prefix causes versioneer to fail completely and return the version as 0+unknown.  Removing these two arguments makes things work again.

Does this warrant some platform special casing?  I'm happy to put a PR forward, but I don't have a feeling for the best way to address this issue.

**Comment by alexwidener** [comment] 2016-09-06 21:32
Seconded.

**Comment by warner** [comment] 2016-12-27 02:12
Huh. what version of git are you using? I'd expect `--match` success or failure to depend upon git, more than on the platform.

Maybe we could change it to watch for a return value that indicates a `--match` -less git (or OS) and fall back to some other flavor of the command. Or run two separate git commands (one with `--match`, one without) and merge their results.

**Comment by alexwidener** [comment] 2016-12-27 02:15
Apologies, I will be unable to contribute to this issue, I filed this when I was at a different job. I recall it happening moderately frequently, as we used Versioneer in our package management system, but I'm not currently in an environment that uses Versioneer in our package management system so I'll be unable to perform any further testing.

**Comment by warner** [comment] 2016-12-27 04:20
No worries.. thanks for confirming it happens in more than one place!

**Comment by henniss** [comment] 2017-08-25 21:40
I can confirm this. git 2.14.0, not that it matters. 

I'm getting a message `fatal: --dirty is incompatible with commit-ishes` when running `python setup.py bdist_wheel`.  It only occurs with an empty `tag_prefix`. 

It looks like the `*` is being globbed on windows, which results in multiple arguments following `--match`. For example, `subprocess.Popen(['echo', '*'])` will result in one argument on unix systems, but many arguments on windows. 

I'll try to dig into this more tonight.

**Comment by drewejohnson** [comment] 2017-09-29 13:47
I too am seeing this issue with versioneer v0.18, but only when using my anaconda distribution of python through cygwin. If I use python 3.6 or 2.7 through cygwin, `python setup.py version` yields the correct version tag. With the anaconda distribution [python 3.5.4], I get the `--dirty is incompatible with commit-ishes` error. I'm using git 2.14.1 as well

**Comment by effigies** [comment] 2020-10-23 12:06
I'm curious if this is resolved by #229.

**Comment by DancingQuanta** [comment] 2021-08-23 18:54
Hi, after some analysis of `versioneer.py` I came up with a fix in my PR #262. Could you try this out please?

**Closed** 2022-07-27 02:33 UTC
